config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "pages/user"
  get "pages/settings"
  get "pages/financialhealth"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

    # Custom routes
  get "user", to: "pages#user"
  get "settings", to: "pages#settings"
  get "financialhealth", to: "pages#financialhealth"
  get "businesscoaches", to: "pages#businesscoaches"
  get "businessresources", to: "pages#businessresources"
  get "healthcare", to: "pages#healthcare"
  get "physicalhealth", to: "pages#physicalhealth"
  get "mentalhealth", to: "pages#mentalhealth"
  get "doctors", to: "pages#doctors"
  get "booking", to: "pages#booking"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # Any logic for the home action goes here
  end

  def user
  end

  def financialhealth
  end

  def businesscoaches
  end

  def settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Telehealth" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'landing_page', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/booking.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Landing Page</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'booking', media: 'all' %>
  </head>
  <body>
    <header class="header">
      <%= image_tag 'logo.png', alt: 'Logo', class: 'logo' %>
      <nav class="navbar">
        <%= link_to 'Home', root_path %>
        <%= link_to 'Pricing', '/about' %>
        <%= link_to 'Revenue Share Model', '/revenue' %>
        <%= link_to 'Becoming a Practitioner', '/practitioner' %>
        <%= link_to 'Our Mission', '/mission' %>
        <%= link_to 'Contact Us', '/contact' %>
      </nav>
      <div class="btn_cont">
        <button>
          Sign up
        </button>
        <div class="btn_cont_divider"></div>
        <button>
          Sign In
        </button>
      </div>
    </header>
    <main>
      <div class="booking">
        <div class="doctor_cont">
          <%= image_tag 'booking.svg', alt: 'logo', class: 'doctor_img' %>
          <div class="doctor_info">
            <span class='doctor_name'>Leticia Meighan</span>
            <span class='doctor_proffesion'>Funct. Med Coach/Hormone Expert</span>
            <div>
              <%= image_tag 'starbold.svg', alt: 'lc1' %>
              <%= image_tag 'starbold.svg', alt: 'lc1' %>
              <%= image_tag 'starbold.svg', alt: 'lc1' %>
              <%= image_tag 'star.svg', alt: 'lc1' %>
              <%= image_tag 'star.svg', alt: 'lc1' %>
            </div>
            <span class='doctor_t1'>Funct. Med Coach/Hormone Expert</span>
            <span class='doctor_t2'>Funct. Med Coach/Hormone Expert</span>
          </div>
        </div>
        <div class="doctor_about">
          <div class="doctor_about_cont1">
            <span class='doctor_name'>About</span>
            <span class='doctor_name'>
              My name is Leticia Meighan and I am a board certified Family Nurse Practitioner since 2012. I have over 20 years experience of working in healthcare, including emergency room, urgent care, and out patient clinics. I have been a Family Nurse Practitioner in Florida doing what I love which serving my community for ten years which includes primary care, acute care, cardiology, and gastroenterology. I have previous experience working with hospitalist in various hospitals In Miami,Florida. I can see patients that range between 16 years old and I can treat acute and chronic illnesses via telemedicine. Part of your visit will include education and healthcare recommendations.
            </span>
          </div>
          <div class="doctor_about_cont2">
            <%= image_tag 'calendar.svg', alt: 'logo', class: 'calendar' %>
            <div class="timeslots">
              <span>Timeslots (Times listed below are in your local timezone) No timeslot</span>
            </div>
            <button>Proceed</button>
          </div>
        </div>
      </div>
      <div class="bonus">
        <span>Get 3 free appointments and a lifelong membership to TeleHealth Today now for just $50!</span>
        <button>Start now</button>
        <%= image_tag 'bonus.svg', alt: 'logo', class: 'bonus_img' %>
      </div>
    </main>
    <footer class="footer">
      <div class="footer_main">
        <div class="footer_col1">
          <%= image_tag 'logo.png', alt: 'logo', class: 'footer_logo' %>
          <div>
            <p class='social_info'>Download the app by clicking the link below</p>
            <div>
              <%= image_tag 'googleplay.png', alt: 'logo', class: 'app_stores' %>
              <%= image_tag 'applestore.png', alt: 'logo', class: 'app_stores' %>
            </div>
          </div>
        </div>
        <div class="pages_col_cont">
          <span class='footer_col_title'>Pages</span>
          <span class='footer_page_content_text'>Home it work</span>
          <span class='footer_page_content_text'>Pricing</span>
          <span class='footer_page_content_text'>Blog</span>
          <span class='footer_page_content_text'>Demo</span>
        </div>
        <div class="pages_col_cont">
          <span class='footer_col_title'>Contact</span>
          <div class="footer_contact_cont">
            <%= image_tag 'callicon.png', alt: 'logo', class: 'app_stores' %>
            <span class='footer_contact_text'>(714) 477-2877</span>
          </div>
          <div class="footer_contact_cont">
            <%= image_tag 'emailicon.png', alt: 'logo', class: 'app_stores' %>
            <span class='footer_contact_text'>Healthtoday@gmail.com</span>
          </div>
          <div class="footer_contact_cont">
            <%= image_tag 'emailicon.png', alt: 'logo', class: 'app_stores' %>
            <span class='footer_contact_text'>1100 W Town and Country Rd Suite 1250 Orange, CA 92868</span>
          </div>
        </div>
        <div class="footer_socials">
          <span class='footer_col_title'>Contact</span>
          <div class="footer_social_icons_cont">
            <%= image_tag 'tiktok.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'snapchat.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'facebook.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'twitter.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'linkedin.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'instagram.png', alt: 'logo', class: 'footer_social_icons' %>
          </div>
        </div>
      </div>
      <div class="footer_btm">
        <span>© 2024 Telehealth Today, LLC. All Rights Reserved.</span>
      </div>
    </footer>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('businesscoach').addEventListener('click', function() {
          window.location.href = "<%= businesscoaches_path %>";
        });
      });
       document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('businessresource').addEventListener('click', function() {
          window.location.href = "<%= businessresources_path %>";
        });
      });
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Landing Page</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'landing_page', media: 'all' %>
  </head>
  <body>
    <header class="header">
      <%= image_tag 'logo.png', alt: 'Logo', class: 'logo' %>
      <nav class="navbar">
        <%= link_to 'Home', root_path %>
        <%= link_to 'Pricing', '/about' %>
        <%= link_to 'Revenue Share Model', '/revenue' %>
        <%= link_to 'Becoming a Practitioner', '/practitioner' %>
        <%= link_to 'Our Mission', '/mission' %>
        <%= link_to 'Contact Us', '/contact' %>
      </nav>
      <div class="btn_cont">
        <button>
          Sign up
        </button>
        <div class="btn_cont_divider"></div>
        <button>
          Sign In
        </button>
      </div>
    </header>
    <main>
      <div class='hero'>
        <%= image_tag 'hero_bg.png', alt: 'hero_img', class: 'hero_img' %>
        <span class='hero_text'>Welcome to TeleHealth Today</span>
      </div>
      <div class="about">
        <%= image_tag 'about.png', alt: 'about', class: 'about_img' %>
        <div class="about_content">
          <span>
            TeleHealth Today is a new free and open marketplace that connects individual businesses and business people to clients that want to talk to them. What type of practitioners we have and the reputation of the practitioners is solely determined by our members. Using governing principles and policies that include letting our practitioners market themselves how they want, and letting the clients they speak to rate them by posting a public review. Our members can also make money by getting their friends to join as we are currently offering an 80% commission to help us launch and capture market share quickly. Click the Links above for details on any of the things mentioned and thank you for being here! 
          </span>
          <button id="booking">
            Book Appointment
          </button>
        </div>
      </div>
      <div class="content">
        <span class="content_title">Choose Who you want to talk to</span>
        <div class="content_cont_row">
          <div class="content_cont" id="financialheight">
            <%= image_tag 'lc1.png', alt: 'lc1' %>
            <div>
              <span class="content_cont_t1">Financial Health</span>
              <span class="content_cont_t2">Standard Care, Preventive Care</span>
            </div>
          </div>
          <div class="content_cont" id="healthcare">
            <%= image_tag 'lc2.png', alt: 'lc2' %>
            <div>
              <span class="content_cont_t1">Healthcare</span>
              <span class="content_cont_t2">Standard Care, Preventive Care</span>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="footer">
      <div class="footer_main">
        <div class="footer_col1">
          <%= image_tag 'logo.png', alt: 'logo', class: 'footer_logo' %>
          <div>
            <p class='social_info'>Download the app by clicking the link below</p>
            <div>
              <%= image_tag 'googleplay.png', alt: 'logo', class: 'app_stores' %>
              <%= image_tag 'applestore.png', alt: 'logo', class: 'app_stores' %>
            </div>
          </div>
        </div>
        <div class="pages_col_cont">
          <span class='footer_col_title'>Pages</span>
          <span class='footer_page_content_text'>Home it work</span>
          <span class='footer_page_content_text'>Pricing</span>
          <span class='footer_page_content_text'>Blog</span>
          <span class='footer_page_content_text'>Demo</span>
        </div>
        <div class="pages_col_cont">
          <span class='footer_col_title'>Contact</span>
          <div class="footer_contact_cont">
            <%= image_tag 'callicon.png', alt: 'logo', class: 'app_stores' %>
            <span class='footer_contact_text'>(714) 477-2877</span>
          </div>
          <div class="footer_contact_cont">
            <%= image_tag 'emailicon.png', alt: 'logo', class: 'app_stores' %>
            <span class='footer_contact_text'>Healthtoday@gmail.com</span>
          </div>
          <div class="footer_contact_cont">
            <%= image_tag 'emailicon.png', alt: 'logo', class: 'app_stores' %>
            <span class='footer_contact_text'>1100 W Town and Country Rd Suite 1250 Orange, CA 92868</span>
          </div>
        </div>
        <div class="footer_socials">
          <span class='footer_col_title'>Contact</span>
          <div class="footer_social_icons_cont">
            <%= image_tag 'tiktok.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'snapchat.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'facebook.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'twitter.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'linkedin.png', alt: 'logo', class: 'footer_social_icons' %>
            <%= image_tag 'instagram.png', alt: 'logo', class: 'footer_social_icons' %>
          </div>
        </div>
      </div>
      <div class="footer_btm">
        <span>© 2024 Telehealth Today, LLC. All Rights Reserved.</span>
      </div>
    </footer>
    <script>
       document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('booking').addEventListener('click', function() {
          window.location.href = "<%= booking_path %>";
        });
      });
    </script>
  </body>
</html>

      <%
=begin%>
 document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('financialheight').addEventListener('click', function() {
          window.location.href = "<%= financialhealth_path %>";
        });
      });
       document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('healthcare').addEventListener('click', function() {
          window.location.href = "<%= healthcare_path %>";
        });
      }); 
<%
=end%>